### ISSUE TITLE
Collect clipboard file transfer

### ISSUE THREAD

**Issue by civic9** [GoSecure/pyrdp#100]
Hi,

Is it possible to store under `pyrdp_output/files` files transfered using clipboard?

Thanks.

**Comment by Res260** [comment]
Hi, for now it is **not** possible. The only thing that is saved is the path to the file. It would be possible to do, but it has not been implemented yet.

**Comment by alxbl** [comment]
Relevant spec: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpeclip/3095a07f-e558-47ca-966e-a54bc9a6c41d
