### ISSUE TITLE
Player should support window scaling

### ISSUE THREAD

**Issue by civic9** [GoSecure/pyrdp#101]
Hi, Some suggestions for the player.

1. Replay window scaling would be very helpful.
2. ~notify2 is totally incompatible with ms-windows, I think. I use the player with import notify2 and its calls commented out (but otherwise it works well, thanks).~ done in #129

**Comment by Res260** [comment]
What kind of error do you get with notify2? We have not tested the app for Windows, so your feedback is appreciated! :)

**Comment by civic9** [comment]
notify2 uses dbus which I don't think has any chance to work in windows. 
https://stackoverflow.com/questions/49972005/no-module-named-dbus-error

Package dbus-python can't be installed on windows, so I removed it from setup.py.
Then notify2 can't work without dbus module:

`Traceback (most recent call last):
  File "bin\pyrdp-player.py", line 23, in <module>
    from pyrdp.logging import LOGGER_NAMES, NotifyHandler
  File "c:\tmp\pyrdp\pyrdp\logging\__init__.py", line 10, in <module>
    from pyrdp.logging.handlers import NotifyHandler
  File "c:\tmp\pyrdp\pyrdp\logging\handlers.py", line 5, in <module>
    import notify2
  File "c:\users\civic9\AppData\Local\Programs\Python\Python36\lib\site-packages\
notify2.py", line 39, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'`

**Comment by obilodeau** [comment]
Windows support, which was recently released, gets rid of notify2.

I'll adjust this issue so that it focuses only on window scaling.

**Comment by alxbl** [comment]
If anyone decides to look at this:

For window scaling, this could be implemented directly in the QRemoteDesktop (`pyrdp/ui/qt.py`) widget by polling the dimensions of the parent window and calling `scaled()` on the `QImage` buffer.
