### ISSUE TITLE
Display doesn't render when disabling fast-path

### ISSUE THREAD

**Issue by Pourliver** [GoSecure/pyrdp#115]
I tested this with Remmina and FreeRDP. Both will successfully establish a connection, but the screen won't render. The input data (cursor, keyboard) still goes through.

To reproduce with Remmina, check the "Disable fast-path" option. With FreeRDP, add "-fast-path" to your command.

**Comment by Res260** [comment]
What about the replay? If you have the live player open, does it show an
image?

**Comment by Pourliver** [comment]
The live player doesn't render, in live or in replay, so we can assume that the bitmap information isn't correctly relayed. I'll look into it later.

**Comment by Pourliver** [comment]
So, this isn't a bug... It's actually a feature. Recent versions of RDP doesn't support slow-path graphics output. 
> Microsoft RDP 7.1 RemoteFX servers and RDP 8.0, 8.1, 10.0, 10.1, 10.2, 10.3, 10.4, and 10.5 servers do not support slow-path graphics output.

Source : https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/cbe1ed0a-d320-4ea5-be5a-f2eb6e032853#Appendix_A_36

**Comment by Pourliver** [comment]
Their documentation is so complicated, why is that information in the appendix instead of the definition of "slow-path graphic update"... Anyway, closing.
