### ISSUE TITLE
Scanning the honeypot doesn't give the expected results

### ISSUE THREAD

**Issue by Pourliver** [GoSecure/pyrdp#126]
On the first image, I try to connect directly to my target (without PyRDP)  with bad credentials, followed by good credentials. We clearly see how we are rejected in the first one, then accepted on the second.

![rdp_tunnel](https://user-images.githubusercontent.com/11776687/60517375-95eb1e80-9cad-11e9-8150-9d8e75c2d87d.png)

On the second image, I connect to the PyRDP honeypot with bad credentials, followed by good credentials. We get the same results in both case, meaning that an attacker would get a ton of false positive if he tried to spray connections attempts.

![rdp_honeypot_filtered](https://user-images.githubusercontent.com/11776687/60517807-46592280-9cae-11e9-9622-119e9cd92f2c.png)

I haven't looked into it yet, but I think it should mirror the first scenario.

**Comment by Pourliver** [comment]
After looking at pcaps for a good part of the day, it makes sense now. Credentials can only be validated when the user logs-in with NLA. So on the first screenshot, the server supported NLA, so my credentials got tested by CredSSP, and the authentication worked as intended.

On the second screenshot, we connect to PyRDP, which will downgrade the connection to RDP or TLS when possible, which have no way of knowing if the credentials worked without GUI.

Maybe I'm wrong, but this is how I understand it.

**Comment by Pourliver** [comment]
This comment seems to confirm my guess

https://github.com/FreeRDP/FreeRDP/issues/2893#issuecomment-230224050

Leaving the issue open if anyone has an idea on how we could integrate this in PyRDP.

**Comment by alxbl** [comment]
I believe there is no way around this unless we support NLA. Without that enabled, the server will always accept a connection to the lock screen and credentials must be input/tested manually.

I'm closing this as it is expected behavior of non-NLA connections.
