### ISSUE TITLE
Building wheel for dbus-python (setup.py) ... error

### ISSUE THREAD

**Issue by ryansecondaccount** [GoSecure/pyrdp#130]
I'm working through the installation on an Ubuntu machine and when I get to the point where I run `pip3 install -U -e .` I am given many errors like:

```
ERROR: Complete output from command /home/rdp/pyrdp/pyrdp/venv/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-cm5qoeyx/dbus-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-j5kwexbp --python-tag cp36:
  ERROR: running bdist_wheel
  running build
```
and
```
checking consistency of all components of python development environment... no
  configure: error: in `/tmp/pip-install-cm5qoeyx/dbus-python/build/temp.linux-x86_64-3.6':
  configure: error:
    Could not link test program to Python. Maybe the main Python library has been
    installed in some non-standard library path. If so, pass it to configure,
    via the LIBS environment variable.
    Example: ./configure LIBS="-L/usr/non-standard-path/python/lib"
    ============================================================================
     ERROR!
     You probably have to install the development version of the Python package
     for your distribution.  The exact name of this package varies among them.
    ============================================================================

  See `config.log' for more details

```
The actual output is super long but I could attach if you'd like. I have followed all of the steps so I am not sure what I am doing wrong.

**Comment by Pourliver** [comment]
Could you please send the full install log? 

A quick guess would be that maybe `pip3` doesn't use your venv. Could you try running `python -m pip install -U -e .` and see if it works like that?

**Comment by ryansecondaccount** [comment]
It looks like the same output as before. I've attached it because it is 1500 lines long.
[output.txt](https://github.com/GoSecure/pyrdp/files/3363843/output.txt)

**Comment by Pourliver** [comment]
I'll take a more in-depth look monday, but from what I can see, it looks like you don't have the python header files, which are commonly needed for a lot packages. They can be installed with the following command if I remember correctly.

`sudo apt install python3-dev`

**Comment by obilodeau** [comment]
This was fixed by #172. Closing. Feel free to re-open if necessary.

**Comment by Blue-Hope** [comment]
`sudo apt-get install libdbus-1-dev libdbus-glib-1-dev`
this works for me

**Comment by masterjoseph914** [comment]
> `sudo apt-get install python3-dev` or `sudo apt-get install python-dev`

I know this question and answers are for Ubuntu, but for those who are like me yesterday who were searching and can't find a solution for Fedora,

In Fedora 34, I did:

    yum search python3 | grep devel

Then it returned bunch of `python3 packages` including `python3-devel`
Then I install it using:

    sudo yum install -y python3-devel.x86_64
