### ISSUE TITLE
Improvement to client drive explorer / filesystem mapping

### ISSUE THREAD

**Issue by Pourliver** [GoSecure/pyrdp#137]
After playing with the drive explorer, and sharing a big folder, it was really painful to look around for files.

I think we should be able to recursively download a folder. I had the idea when I saw a .git folder, but it could apply to so much more.

I also thing we should be able to configure some kind of auto-scrapping. We would need to have some kind of crawler that could look around for some interesting extensions like txt, xls, doc, and all that should be configurable. Since it is very rare to have someone connect, and the odds of that connection happening while we are monitoring with the PyRDP player is very low, we should have a way to automatically download files that the crawler found without the pyrdp-player.

Maybe that the crawler / auto-download should be built in the pyrdp-mitm directly, and the recursive download in the pyrdp-player. What do you think?

**Comment by Pourliver** [comment]
We would also need a way to rapidly identify connections with a mounted drive in the pyrdp-player. I think we should add an icon to the connection tab, and even prompt before closing the connection.

**Comment by xshill** [comment]
Auto-download in pyrdp-mitm makes sense to avoid missing something if the player is not open. Recursive downloads could also go in pyrdp-mitm for the same reason. You could use it to automatically download all .git folders for example.

**Comment by Res260** [comment]
Implemented in #140 and #141
