### ISSUE TITLE
PyRDP hangs when downloading a file of 108 bytes on the client's shared drive

### ISSUE THREAD

**Issue by Pourliver** [GoSecure/pyrdp#139]
Weird enough, the player hangs when trying to download a file of 108 bytes. Tested with a Windows 10 client. I can add more detail if needed, but I don't really know what would help with this issue.

**Comment by Pourliver** [comment]
The maximum "payload" size that the client can send is 2^14, so 16384. I scripted the creation of these files, and tried to download them all. 

The only one that hanged was 108 bytes, and every other N * 2^14 + 108.

**Comment by alxbl** [comment]
This is still reproducible. There's a lot of noise on the device redirection channel, so it's very hard to track what is happening to compare working transfers with non-working transfers. We'll need to add some debug code to help investigate this.

So far I compared two files (one working, one not) and I noticed that the transfer hangs on/after an IORequest from the client to MJ_READ the file descriptor. The working file doesn't have a single READ call, so I'm thinking this might be related, but will need to find time to dig deeper...

**Comment by alxbl** [comment]
NOTE: While we instrument this, we should address #222 since it's located in the same code area, and maybe shed some light on this.

**Comment by obilodeau** [comment]
![2022-11-15_15-06](https://user-images.githubusercontent.com/546325/202015192-9611cebf-3b3b-4e44-8844-85bdadbd1255.png)

Managed to fix this at the same time of another issue.

**Comment by Res260** [comment]
My brother in christ I'm no sad I cant have closure on this bug

**Comment by Res260** [comment]
Wait i didnt read properly i'm glad to have closure on this bug* 😂
