### ISSUE TITLE
pyrdp-player Could not get owner of name 'org.freedesktop.Notifications': no such name

### ISSUE THREAD

**Issue by SnasiCze** [GoSecure/pyrdp#143]
Run on Debian Linux debian-s-2vcpu-2gb-fra1-01 4.19.0-5-cloud-amd64 #1 SMP Debian 4.19.37-5+deb10u2 (2019-08-08) x86_64 GNU/Linux

I tried to reinstall all packages and nothing.
I don't know what the problem is.
```
Traceback (most recent call last):
  File "/home/snasel/clone/pyrdp/venv/lib/python3.7/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/home/snasel/clone/pyrdp/venv/lib/python3.7/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/home/snasel/clone/pyrdp/venv/lib/python3.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.Notifications': no such name


Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.


```

**Comment by obilodeau** [comment]
This probably happens because `DBus` isn't running (since this is a cloud server). What happens when you run `dbus-monitor`?

**Comment by SnasiCze** [comment]
when i run `dbus-monitor` 
`snasel@debian-s-2vcpu-2gb-fra1-01:~$ dbus-monitor
signal time=1566455216.953951 sender=org.freedesktop.DBus -> destination=:1.57 serial=2 path=/org/freedesktop/DBus; i                                        nterface=org.freedesktop.DBus; member=NameAcquired
   string ":1.57"
signal time=1566455216.954174 sender=org.freedesktop.DBus -> destination=:1.57 serial=4 path=/org/freedesktop/DBus; i                                        nterface=org.freedesktop.DBus; member=NameLost
   string ":1.57"
method call time=1566455236.058649 sender=:1.58 -> destination=org.freedesktop.DBus serial=1 path=/org/freedesktop/DB                                        us; interface=org.freedesktop.DBus; member=Hello
method return time=1566455236.058781 sender=org.freedesktop.DBus -> destination=:1.58 serial=1 reply_serial=1
   string ":1.58"
signal time=1566455236.058798 sender=org.freedesktop.DBus -> destination=(null destination) serial=5 path=/org/freede                                        sktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.58"
   string ""
   string ":1.58"
signal time=1566455236.058823 sender=org.freedesktop.DBus -> destination=:1.58 serial=2 path=/org/freedesktop/DBus; i                                        nterface=org.freedesktop.DBus; member=NameAcquired
   string ":1.58"
method call time=1566455236.059161 sender=:1.58 -> destination=org.freedesktop.DBus serial=2 path=/org/freedesktop/DB                                        us; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.freedesktop.Notifications"
error time=1566455236.059236 sender=org.freedesktop.DBus -> destination=:1.58 error_name=org.freedesktop.DBus.Error.N                                        ameHasNoOwner reply_serial=2
   string "Could not get owner of name 'org.freedesktop.Notifications': no such name"
signal time=1566455236.061397 sender=org.freedesktop.DBus -> destination=org.freedesktop.systemd1 serial=21 path=/org                                        /freedesktop/DBus; interface=org.freedesktop.systemd1.Activator; member=ActivationRequest
   string "dunst.service"
method call time=1566455236.061490 sender=:1.58 -> destination=org.freedesktop.DBus serial=3 path=/org/freedesktop/DB                                        us; interface=org.freedesktop.DBus; member=StartServiceByName
   string "org.freedesktop.Notifications"
   uint32 0
signal time=1566455261.156821 sender=org.freedesktop.DBus -> destination=:1.58 serial=6 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.58"
signal time=1566455261.156971 sender=org.freedesktop.DBus -> destination=(null destination) serial=7 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.58"
   string ":1.58"
   string ""`

**Comment by Res260** [comment]
Are you running the pyrdp player on a machine without a graphical interface?

**Comment by SnasiCze** [comment]
Yes, the player runs on a server without a graphical interface. Sometimes I use xming.

**Comment by Res260** [comment]
The PyRDP player requires a graphical interface, as it is used to view RDP sessions. The PyRDP MITM  doesnt require a graphical interface!

**Comment by Norup123** [comment]
Im having this same issue on Ubuntu 18.04
Running `dbus-monitor` gives me this output 
![image](https://user-images.githubusercontent.com/54578187/63845094-afe16e80-c989-11e9-94b9-69a2c4f48a05.png)

**Comment by Norup123** [comment]
![image](https://user-images.githubusercontent.com/54578187/63937149-0e7a1b80-ca62-11e9-8a68-734e844c255b.png)

**Comment by Res260** [comment]
Does the machine have a graphical output (is it a server?)

**Comment by Norup123** [comment]
Yes it is a regular install of ubuntu 18.04. Graphical interface and all

**Comment by Norup123** [comment]
Do you know of a quick workaround for this, if its not an issue you can fix? :)

**Comment by obilodeau** [comment]
Can you give the output of `systemctl status dbus.service`?

In a properly activated `venv` you shouldn't need `sudo` to do the pip installs.

Can you deactivate the venv (or close the shell and open a new one) and re-do the installation steps without sudo for pip and post the output of the commands. Thanks and good luck!

**Comment by Norup123** [comment]
dbus is running:
![image](https://user-images.githubusercontent.com/54578187/64112498-e7845800-cd87-11e9-8ca6-483b085a0ceb.png)

**Comment by obilodeau** [comment]
After more digging, I think the problem could be that you have no notification daemon started. Or a PyQT bug regarding interactions with such daemon. Or that in the way your virtual env got setup there is a communication problem between the PyQT code and the dbus notification service.

According to the above screenshots you seem to be using Unity (Ubuntu 18.04's default) is that correct? If so, do you have `notify-osd` installed and started?

Here is some Arch Linux docs about notification daemons: https://wiki.archlinux.org/index.php/Desktop_notifications#Notification_servers
Bionic's list of packages that would satisfy the `notification-daemon` requirement: https://packages.ubuntu.com/bionic/x11/notification-daemon

**Comment by obilodeau** [comment]
@SnasiCze, @Norup123 I'll assume you got it working and close the issue. Feel free to re-open if that's not the case.
