### ISSUE TITLE
Debian 9.11.0 (Stretch) - PySide2

### ISSUE THREAD

**Issue by supaplextor** [GoSecure/pyrdp#150]
From README.md:

Finally, you can install the project with Pip:

```
pip3 install -U pip setuptools wheel
pip3 install -U -e .
```

This should install all the dependencies required to run PyRDP.

-----

Unable to install PySide2:

```
(venv) supaplex@pobox13:~/pyrdp$ pip3 install -U PySide2
Collecting PySide2
  ERROR: Could not find a version that satisfies the requirement PySide2 (from versions: none)
ERROR: No matching distribution found for PySide2

```

**Comment by Res260** [comment]
Could you please provide details on your OS type and version, as well as your pip version and your python version? Thanks

**Comment by supaplextor** [comment]
```
supaplex@pobox13:~$ uname -a
Linux pobox13 4.9.0-11-686-pae #1 SMP Debian 4.9.189-3 (2019-09-02) i686 GNU/Linux
```
I forgot this was a one-off box, most of my thin clients are running 10.0 buster, but not this one. I went to oldstable to get virtualbox 5.2.32 running. I have a windows vm for the rdp target.

I did some research in the meantime, and I found PySide2 doesn't support 32bit...

Debian Linux 32bit,

```
python      python2.7   python3.5   python3m    
python2     python3     python3.5m  
supaplex@pobox13:~$ which python
/usr/bin/python
supaplex@pobox13:~$ readlink `!!`
readlink `which python`
python2.7
supaplex@pobox13:~$ dpkg -S `which python2.7`
python2.7-minimal: /usr/bin/python2.7
supaplex@pobox13:~$ dpkg -l python2.7-minimal
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  python2.7-mini 2.7.13-2+deb i386         Minimal subset of the Python lang
supaplex@pobox13:~$ dpkg -S `which python3.5`
python3.5-minimal: /usr/bin/python3.5
supaplex@pobox13:~$ dpkg -l python3.5-minimal
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  python3.5-mini 3.5.3-1+deb9 i386         Minimal subset of the Python lang
```

**Comment by Res260** [comment]
We indeed never tried to install PyRDP on a 32bit system. I'll add it in the readme that it only works on 64bits systems. Thanks for your report and feel free to open another issue if you have a potential fix! :)

**Comment by obilodeau** [comment]
For the record, it is [QT that doesn't provide 32-bit binaries anymore since 5.6](http://disq.us/p/2437gru) not PySide2.

Also,
```
supaplex@pobox13:~$ readlink `!!`
readlink `which python`
python2.7
```

PyRDP is a python3 project but this doesn't change the conclusion.

Lastly, PySide2 is just required if you want to operate the player. The man-in-the-middle should work without it. If it doesn't feel free to file another bug.

**Comment by supaplextor** [comment]
Looks like I wasn't in the venv on part of this. pyrdp-mitm.py has the full path of venv/bin/python3 on line 1. As you'll see, this is not pobox13. rdp-balance is the suggested 64bit ubuntu (and works okay).

```
(venv) supaplex@rpd-balance:~/Projects/rdp-bait/pyrdp$ which pyrdp-mitm.py
/home/supaplex/Projects/rdp-bait/pyrdp/venv/bin/pyrdp-mitm.py
(venv) supaplex@rpd-balance:~/Projects/rdp-bait/pyrdp$ head -n 1 `!!`
head -n 1 `which pyrdp-mitm.py`
#!/home/supaplex/Projects/rdp-bait/pyrdp/venv/bin/python3
(venv) supaplex@rpd-balance:~/Projects/rdp-bait/pyrdp$ which python3
/home/supaplex/Projects/rdp-bait/pyrdp/venv/bin/python3
(venv) supaplex@rpd-balance:~/Projects/rdp-bait/pyrdp$ readlink `!!`
readlink `which python3`
/usr/bin/python3
(venv) supaplex@rpd-balance:~/Projects/rdp-bait/pyrdp$ readlink /usr/bin/python3
python3.6

```

**Comment by obilodeau** [comment]
Now that the GUI is optional. PyRDP should work on 32-bit operating systems. This work has been merged in master and should be released soon.
