### ISSUE TITLE
Make the GUI an optional feature?

### ISSUE THREAD

**Issue by obilodeau** [GoSecure/pyrdp#151]
Due to #150 issue (QT 5 no longer provides binaries for x86 32-bit) PyRDP doesn't work on 32-bit OS.

However, it would be possible to specify the GUI as an optional feature using Python's `extra_requires` section in `setup.py`: https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies. Also, we could specify which console entrypoint requires the optional dependency (spoiler, it's `pyrdp-player.py`).

This would make PyRDP's `pyrdp-mitm.py` work in headless environments and 32-bit environments in one go. We could also get rid of the DBus dependency and its related issues.

If we implement it, we should remember to:
* get rid of dbus-python and notify2 alongside with PySide2
* adjust README to pull in optional dependency by default but explain the alternative
* revert 0794b5e04

Instead of doing the work I opened an issue because I would like to know if people think the headless option is valuable. I won't do it if no one is to use it.

**Comment by Res260** [comment]
For the honeypot use case, the player and the mitm are usually separated, so I think it would make sense. #150 is not the first issue with this problem.

**Comment by robeving** [comment]
I'd also like to run  pyrdp-player.py without a GUI so that it just produces a log file result

**Comment by Res260** [comment]
@robeving What kind of log are you interested in?

**Comment by robeving** [comment]
At the moment I'm converting from an existing PCAP so I don't get any display updates. But creds, keylogs, clipboard and files is what i'm interested in.

**Comment by obilodeau** [comment]
@robeving, I created a ticket to track your good suggestion: #163 

Back to the issue at hand, I just wanted to document that PySide2 pulls in 449MB in our docker image:

![pyside2-size](https://user-images.githubusercontent.com/546325/68222947-e0610c80-ffb9-11e9-915b-f5a162ce07f8.png)
