### ISSUE TITLE
Better apt-get in Dockerfile

### ISSUE THREAD

**Issue by ondrg** [GoSecure/pyrdp#156]
There are at least three things what should be updated in Dockerfile:

1) `apt-get update` and `apt-get install` is better run together because Docker could cache `apt-get update` for a long time
2) `apt-get install` in two `RUN` commands create a additional image layer
3) delete apt cache after install packages saves ~30 MB of image size

Source: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

**Comment by xshill** [comment]
Closed with #157.
