### ISSUE TITLE
pyrdp-mitm.py ignores NLA flag

### ISSUE THREAD

**Issue by gilazr** [GoSecure/pyrdp#167]
The main function declares this argument, that is never used. I can't seem to use NLA client authentication with PyRDP. Is it even supported?
`parser.add_argument("-n", "--nla", help="For NLA client authentication (need to provide credentials)", action="store_true")`

Thank you,
Gil

**Comment by Res260** [comment]
I have removed the argument, as NLA authentication is **not** supported in PyRDP at the moment. It could be implemented, but NLA is a mechanism that strongly mitigates MITM attacks, so for it to work we need to control the destination server.

0476777cff25e02c2a017c5c12a1d67428bf14d4

Sorry for the confusion!

**Comment by gilazr** [comment]
Thank you for your answer
