### ISSUE TITLE
Implement a twistd plugin

### ISSUE THREAD

**Issue by obilodeau** [GoSecure/pyrdp#174]
Right now one of our deployments reliably crashes from time to time. I would like to be able to debug it. The `twistd` launcher supports a `--debug` option that when the process is sent a `SIGUSR2`, it drops into a `pdb` debugging shell.

The problem is that our project doesn't provide a `twistd` compatible plugin. I would like to create one but also maintain the `pyrdp-mitm.py` launcher. One of my concerns is that it will impact logging.

Ref: https://twisted.readthedocs.io/en/twisted-18.4.0/core/howto/tap.html

**Comment by Res260** [comment]
>Right now one of our deployments reliably crashes from time to time

Meaning it crashes often but not always? 🤔

**Comment by obilodeau** [comment]
> Meaning it crashes often but not always? :thinking:

Meaning it always crashes but it takes a while. Where _a while_ is an undetermined amount of time and triggered by an unknown condition.

**Comment by obilodeau** [comment]
Implemented in #177.
