### ISSUE TITLE
Logs and recordings are difficult to correlate

### ISSUE THREAD

**Issue by obilodeau** [GoSecure/pyrdp#180]
There is no clear link between json events and a given recording file.

There are actually two problems:
* Filename on their own mean nothing (can't go from filename to logs)
* Logs don't contain a reference to a given replay filename (can't go from json events to replay file)

**Comment by Res260** [comment]
The simplest solution would be to append the id/friendlyname of the connection (ex charlie71846) to the name of the replay file imo. It should be an easy change

**Comment by obilodeau** [comment]
Yes, I already have something almost working but I'm working on having the replay filename in the logs too.

The way my ELK dashboard is setup, using the nice "Connection report" you've made, I would hunt for the correct log files. Without that there is a potential collision on the sessionID if we collect over several IPs for months. Just to give you an idea we had 3208 unique sessions in the last 12 hours on a single IP (2.5M+ events total). Of course, filtering by date would be fine but why just not add it anyway ;) Makes searching in the filesystem quicker too.
