### ISSUE TITLE
Check for credentials only

### ISSUE THREAD

**Issue by ariadarkkkis** [GoSecure/pyrdp#184]
I want to use this as a library in my program and I just want it to check for credentials with NLA.
I want to give it IP, username and password and it checks if they are valid or not.
Any helps with this?

**Comment by obilodeau** [comment]
We don't support NLA at the moment.

**Comment by ariadarkkkis** [comment]
Any way to make rdpy to check for credentials only?

**Comment by Res260** [comment]
@ariadarkkkis NLA is a step before the rest of the RDP connection sequence (minus the first 2 packets). If we were to implement NLA support, it would be trivially easy to plug it with the rest of the RDP connection. This means that "implementing NLA" and "make pyrdp check for credentials only" is the same thing (ish), development-wise.

I assume that you mean check for credentials using NLA.

**Comment by ariadarkkkis** [comment]
Yea I just want to check some credentials using NLA. I dont want  to fully connect to session. Just checking working credentials only.

**Comment by obilodeau** [comment]
As I stated before, we currently don't support NLA. If you are interested, you can implement client-side NLA support and we might merge this code if it fits our current architecture. That would be awesome!

Otherwise, for your use case, I would look at instrumenting FreeRDP directly. It is the most comprehensive RDP client.

**Comment by ariadarkkkis** [comment]
@obilodeau I have this issue with FreeRDP ( I dont know if its only me or the compiled version have this issue). I tried using Hydra ( which for RDP brute, it uses Freerdp ) with 100 threads, it maxed out 100% cpu usage on a 12 core E5 CPU. I didnt count how many freerdps are running but most of them were running at 2-5% CPU usage each and some of them more than 10-20% cpu usage. Thats why I didnt go for FreeRDP but it does exactly what I want.

**Comment by obilodeau** [comment]
Unfortunately, we don't support your use case right now. If you are interested you can dig in the code, it should be fairly approachable. Otherwise, this is not a FreeRDP support channel. If you have performance problems, take your question to them.
