### ISSUE TITLE
Certificate generation failed, starting docker container

### ISSUE THREAD

**Issue by FraggleR0ck** [GoSecure/pyrdp#216]
When attempting to run the docker container. Not sure if it's something I'm doing wrong. 

docker run -p 3389:3389 gosecure/pyrdp pyrdp-mitm.py 10.x.x.x

[2020-04-17 01:41:50,001] - INFO - GLOBAL - pyrdp.mitm - Generating a private key and certificate for SSL connections
[2020-04-17 01:41:50,012] - ERROR - GLOBAL - pyrdp.mitm - Generation failed. Please provide the private key and certificate with -k and -c
[2020-04-17 01:41:50,013] - ERROR - GLOBAL - pyrdp - An error occurred when creating the server TLS context. There may be a problem with your private key or certificate (e.g: signature algorithm too weak). Here is the exception: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'file_ctrl', 'system lib'), ('SSL routines', 'SSL_CTX_use_certificate_file', 'system lib')]

**Comment by alxbl** [comment]
I doubt that this is going to be version related since we are having successful builds on the CI with the same docker image. I have a hunch it could be an entropy related issue.

Could you provide your docker version? (`docker version`)

Alternatively, this might not be optimal, but if you don't feel like troubleshooting, you can generate a self-signed certificate with `openssl` on the host and provide the key using `-k private.key -c public.crt`

**Comment by Res260** [comment]
Also did you pull the image from dockerhub or you built the docker image from source?

**Comment by Res260** [comment]
> I doubt that this is going to be version related since we are having successful builds on the CI with the same docker image.

The CI only tests docker image building, not running

**Comment by Res260** [comment]
I'm having the same issue when running:

```
git clone ...
docker build -t pyrdp .
docker run -p 3389:3389 pyrdp pyrdp-mitm.py 10.0.0.0
```

![image](https://user-images.githubusercontent.com/14599855/79580835-9b2c2500-8097-11ea-825c-dbea0c55ce36.png)

**Comment by Res260** [comment]
found the error: 
![image](https://user-images.githubusercontent.com/14599855/79582284-90728f80-8099-11ea-99ee-de59a81e78cc.png)

**Comment by FraggleR0ck** [comment]
> Also did you pull the image from dockerhub or you built the docker image from source?

Res260, I pulled the docker image, currently using docker version Docker version 19.03.8, build afacb8b7f0

**Comment by Res260** [comment]
@FraggleR0ck I found the problem and pr #218 is open to fix it. Thanks for your report!

**Comment by alxbl** [comment]
Good catch @Res260! I'm pretty sure that the MITM had worked in docker before (we use it in our honeypots), so this must have been a regression. I'll review the PR and merge!

**Comment by Res260** [comment]
Yeah I think it might have come with the latest docker changes or even something out of our control, i'm really not sure

**Comment by obilodeau** [comment]
It's not a regression, it has never been part of our `Dockerfile`. On the honeypots, @L3houx made sure certificates were created outside of docker by ansible and passed them in via a volume.

**Comment by Res260** [comment]
@obilodeau It's weird since openssl is required by PyOpenSSL which is a pyrdp MITM dependency. Maybe it was installed as a recommanded package but --no-install-recommand removed it? just an hypothesis

**Comment by alxbl** [comment]
> @obilodeau It's weird since openssl is required by PyOpenSSL which is a pyrdp MITM dependency. Maybe it was installed as a recommanded package but --no-install-recommand removed it? just an hypothesis

Pretty sure PyOpenSSL doesn't check for the presence of OpenSSL until it tries to call into the shared object, and then you'd get an exception.

In this case it's a call to `system` so it just fails silently :) and then we fail when trying to open a non existent file.
