### ISSUE TITLE
Avoid refetching dependencies when updating code in docker image

### ISSUE THREAD

**Issue by Res260** [GoSecure/pyrdp#217]
Currently, when changing code in pyrdp and rebuilding the image, the dockerfile fetches the dependencies again because the whole pyrdp folder is copied before the dependencies are fetched, increasing build time considerably. 

There should be a way to fetch dependencies before copying the pyrdp code in the docker image.

**Comment by obilodeau** [comment]
Which dependencies? The OS or pip?

**Comment by Res260** [comment]
Yeah it was not clear, i'm talking about **pip dependencies**.

**Comment by alxbl** [comment]
How sure are we that the GitHub CI will keep the docker images in cache? This might be pointless if GitHub doesn't keep the images around. 

In any case, if it's possible it would save us a lot of CI minutes and really speed up the PR check process.

**Comment by Res260** [comment]
I'm not sure about docker caching for github workflows...

I opened the PR because I was fixing a bug which was docker-dependant and to debug I needed to change the codebase some times, but everytime I did it it pulled the whole dependencies, filling my storage space because it was a new (big) cache layer. It's mostly for this use case that it's problematic I think

**Comment by alxbl** [comment]
I mean, it would be clean to have the dependencies as a separate layer, I agree. If it boosts the CI times at the same time, then that would be nice.

**Comment by obilodeau** [comment]
I can try to address this. However, I recall having to add explicitly a copy of the whole source tree for the pip install step.

Also note that no matter what changes in the code, the runtime image **will be rebuilt**, so even if we can skip some of the `pip install` time spent, the runtime `apt-get` will take place. I was aware when I transitioned to the multi-stage build. The tradeoff is a space-savings (all of our users) vs dev wait time (devs, CI clock time). The solution to that that I've seen is to use a traditional fat full-build Dockerfile for development. A `Dockerfile.dev` that doesn't use multi-stage but that developers use for testing.

**Comment by obilodeau** [comment]
I have to admit that building that image is quite long now with pyside2, pyav, dbus-python all being compiled for an unrelated code change.

I should have something that improves things a little shortly.
