### ISSUE TITLE
PyRDP and Bettercap

### ISSUE THREAD

**Issue by Ondrik8** [GoSecure/pyrdp#278]
````
(venv) ┌──(root💀kali)-[~/src/caplets]
└─# bettercap -iface eth0 -caplet rdp-proxy/rdp-sniffer.cap -eval "set rdp.proxy.command $(which pyrdp-mitm.py)"
bettercap v2.28 (built for linux amd64 with go1.15.6) [type 'help' for a list of commands]

192.168.1.0/24 > 192.168.1.61  » [16:12:24] [sys.log] [inf] arp.spoof arp spoofer started, probing 256 targets.
[16:12:24] [sys.log] [inf] arp.spoof starting net.recon as a requirement for arp.spoof
[16:12:24] [sys.log] [err] error while running caplet rdp-proxy/rdp-sniffer.cap: unknown or invalid syntax "rdp.proxy on", type help for the help menu.
192.168.1.0/24 > 192.168.1.61  » [16:12:24] [endpoint.new] endpoint 192.168.1.72 detected as 10:c3:7b:19:45:e7 (ASUSTek COMPUTER INC.).
192.168.1.0/24 > 192.168.1.61  » [16:12:31] [endpoint.new] endpoint 192.168.1.42 detected as 08:00:27:e4:d3:77 (PCS Computer Systems GmbH).
192.168.1.0/24 > 192.168.1.61  » [16:12:32] [endpoint.new] endpoint 192.168.1.52 detected as 48:f1:7f:d8:72:96.
192.168.1.0/24 > 192.168.1.61  » [16:12:40] [endpoint.lost] endpoint 192.168.1.42 08:00:27:e4:d3:77 (PCS Computer Systems GmbH) lost.
192.168.1.0/24 > 192.168.1.61  » [16:12:47] [endpoint.lost] endpoint 192.168.1.52 48:f1:7f:d8:72:96 lost.
192.168.1.0/24 > 192.168.1.61  » [16:12:49] [endpoint.new] endpoint 192.168.1.53 detected as 28:28:5d:e7:ea:bc (Zyxel Communications Corporation).
192.168.1.0/24 > 192.168.1.61  » [16:12:53] [endpoint.new] endpoint 192.168.1.52 detected as 48:f1:7f:d8:72:96.
192.168.1.0/24 > 192.168.1.61  » [16:12:58] [endpoint.lost] endpoint 192.168.1.53 28:28:5d:e7:ea:bc (Zyxel Communications Corporation) lost.
192.168.1.0/24 > 192.168.1.61  » [16:13:03] [endpoint.lost] endpoint 192.168.1.52 48:f1:7f:d8:72:96 lost.
192.168.1.0/24 > 192.168.1.61  » [16:13:10] [endpoint.new] endpoint 192.168.1.52 detected as 48:f1:7f:d8:72:96.
192.168.1.0/24 > 192.168.1.61  » [16:13:19] [endpoint.new] endpoint 192.168.1.53 detected as 28:28:5d:e7:ea:bc (Zyxel Communications Corporation).
192.168.1.0/24 > 192.168.1.61  » [16:13:21] [endpoint.lost] endpoint 192.168.1.52 48:f1:7f:d8:72:96 lost.
192.168.1.0/24 > 192.168.1.61  » [16:13:27] [endpoint.new] endpoint 192.168.1.52 detected as 48:f1:7f:d8:72:96.
192.168.1.0/24 > 192.168.1.61  » [16:13:29] [endpoint.lost] endpoint 192.168.1.53 28:28:5d:e7:ea:bc (Zyxel Communications Corporation) lost.
192.168.1.0/24 > 192.168.1.61  » [16:13:38] [endpoint.lost] endpoint 192.168.1.52 48:f1:7f:d8:72:96 lost.

````

**Comment by Ondrik8** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/59111771/104460523-43d3ca80-55bf-11eb-9904-f55aa49af10b.png)

**Comment by Ondrik8** [comment]
sorry i messed up with bettercap versions

**Comment by sawafiltseva** [comment]
i have the same problem. witch version of bettercap helped you fix this problem?

**Comment by obilodeau** [comment]
@sawafiltseva you need to use our fork of bettercap. The upstream project never accepted the strategy we used for our caplet so we kept it as a fork. The fork is here and the branch to use is called `rdp-mitm`: https://github.com/GoSecure/bettercap/tree/rdp-mitm. More instructions are here: https://github.com/GoSecure/pyrdp/blob/master/docs/bettercap-rdp-mitm.md

Note that since we built this, we implemented a transparent proxy mode in PyRDP. This means that you can use bettercap in generic arp poison mode and pyrdp in transparent proxy mode to avoid using the fork. I don't think it has been documented except in a Defcon demo Labs that you can see here: https://www.youtube.com/watch?v=1q2Eo3x3u0g. Seek until transparent proxying.

**Comment by sawafiltseva** [comment]
> @sawafiltseva you need to use our fork of bettercap. The upstream project never accepted the strategy we used for our caplet so we kept it as a fork. The fork is here and the branch to use is called `rdp-mitm`: https://github.com/GoSecure/bettercap/tree/rdp-mitm. More instructions are here: https://github.com/GoSecure/pyrdp/blob/master/docs/bettercap-rdp-mitm.md
> 
> Note that since we built this, we implemented a transparent proxy mode in PyRDP. This means that you can use bettercap in generic arp poison mode and pyrdp in transparent proxy mode to avoid using the fork. I don't think it has been documented except in a Defcon demo Labs that you can see here: https://www.youtube.com/watch?v=1q2Eo3x3u0g. Seek until transparent proxying.

-------------------

thanks for your answer. but trouble in all stages of this topic. when i run pyrdp from docker it also not working. just nothing happens. when try use it from git repository all starts but nothing happens witch is full unlike the video. have you ready os snapshot like linux on virtualbox or wmvare or any other solution for it?  
Also your bettercap repository cant be installed the reason of pyrdp.proxy module error. I NEED ANY HELLP OF THIS TOPIC PLEASE. I HOPE TO YOUR UNDERSTANDING. / THANKS
