### ISSUE TITLE
Change pyrdp-convert output paths.

### ISSUE THREAD

**Issue by xshill** [GoSecure/pyrdp#312]
I think the way we output stuff from pyrdp-convert could be improved:

- The output path will always be a folder that will be created by the tool.
- A new subfolder will be created for every session, which will contain the replay / mp4 file, the files folder and the filesystems folder.

**Comment by obilodeau** [comment]
This might have been implemented in #311

**Comment by obilodeau** [comment]
This was implemented in #311
