### ISSUE TITLE
Parsing a decrypted PDU-L7 Pcap with multiple sessions does not work

### ISSUE THREAD

**Issue by obilodeau** [GoSecure/pyrdp#313]
I am able to reliably reproduce a bug where a Pcap with exported PDUs containing more than one session of the same source and destination IPs is getting mixed up and doesn't convert to the correct replay file or mp4.

We should probably cleanly separate streams in the PDU parsing code. Not sure how to do that with PDU level packets (is the information available in the wireshark trace?).

Workaround: walking the pcap with filters like `tcp.stream eq <1, 2, .. N>` and exporting one PDU-L7 pcap per TCP streams works.

**Comment by alxbl** [comment]
I think exported PDUs don't have proper source/dst information, so all streams get mangled together into one big soup. We should check if there's any info in the exported PDUs that could make it possible to distinguish

**Comment by obilodeau** [comment]
Good point @alxbl! I'll check but if what we need to distinguish isn't available, we will simply update our instructions to differentiate streams before exporting and document the limitation.
