### ISSUE TITLE
Pyrdp-converter

### ISSUE THREAD

**Issue by jmmalcala** [GoSecure/pyrdp#324]
Hi team!

I´m triying to export a plaintext PDU pcap file to MP4, but Pyrdp-converter shows me the following error:

pyrdp-convert.py --src 10.10.15.1 --dst 10.10.15.135 -o video -f mp4 exported.pcap                              
[*] Analyzing PCAP 'exported.pcap' ...
    - 10.10.15.1 -> 10.10.15.135: plaintext
[*] Processing 10.10.15.1 -> 10.10.15.135
/home/kali/pyrdp/bin/pyrdp-convert.py:442: DeprecationWarning: an integer is required (got type EDecimal).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  ts = time.strftime("%Y%M%d%H%m%S", time.gmtime(ts))

**[-] Failed: unsupported operand type(s) for +=: 'PosixPath' and 'str'**

Could you help me?

Thank you so much.

**Comment by obilodeau** [comment]
The convert tool was heavily refactored in this PR https://github.com/GoSecure/pyrdp/pull/311 which should be merged soon. I quickly tested in that branch and didn't experience your issue.

If you are using an install from source (GitHub clone), simply switch branch and try again:

```
git switch pcap-fix
pyrdp-convert.py --src 10.10.15.1 --dst 10.10.15.135 -o video -f mp4 exported.pcap
```

**Comment by obilodeau** [comment]
The PR I mentioned above was merged this morning. You can try to do your conversion using master now. Feel free to re-open this issue if it didn't fix your problem.
