### ISSUE TITLE
No password request window

### ISSUE THREAD

**Issue by danielsantos1234** [GoSecure/pyrdp#347]
When I connect to the server normally it always asks for login and password in a popup window:
![1](https://user-images.githubusercontent.com/89299326/130318754-2ffbbf6a-4aaa-4258-86a1-c9a3fa3ad5be.png)
When I connect through pyrdp it goes directly to Windows login screen (without a popup window as shown above) and Windows asks to enter password:
![2](https://user-images.githubusercontent.com/89299326/130318867-3fce90b2-c0d8-4ca7-b872-2249ca7ebcbd.png)
I'm running pyrdp with the following parameters: --transparent --no-replay -l 20000 --no-files and traffic is redirected to pyrdp with iptables:
iptables -t mangle -A PREROUTING -p tcp --dport 3389 -j TPROXY --tproxy-mark 1 --on-port 20000 --on-ip 127.0.0.1

**Comment by Res260** [comment]
This problem had us digging a lot in the past. I think it came down to the fact that the windows RDP Client (mstsc.exe) will not send cached credentials to a server if both of these are true:

1. The client previously connected to `Server A` using Network-Level Authentication (NLA).
2. `Server A` does not support NLA for the current connection.

This is probably what happens here. @alxbl @obilodeau do you remember if this was the conclusion we arrived to?

**Comment by obilodeau** [comment]
@Res260 is right. The server you are connecting to supports both NLA and non-NLA authentication. NLA is the technology that introduced the popup dialog that asks for credentials. PyRDP cannot MITM NLA without the server's private key so it is downgrading the server's offer to use a graphical login instead.

The behavior you have is expected.

**Comment by danielsantos1234** [comment]
Is this technically possible to MITM NLA without the server's private key?
What's the PyRDP behavior when a client connects to the server with the same settings with Remmina or other software?

**Comment by obilodeau** [comment]
> Is this technically possible to MITM NLA without the server's private key?

Not to my knowledge unless we find an implementation flaw. We discussed relay opportunities but we haven't explored that area and we do not plan to do so in the near term or midterm.

> What's the PyRDP behavior when a client connects to the server with the same settings with Remmina or other software?

Same as with `mstsc.exe`: with NLA you get a prompt for credentials (inside Remmina or other clients), in non-NLA you get a full graphical login window.

**Comment by danielsantos1234** [comment]
Is this possible to collect credentials if NLA is required (using --nla-redirection-host)? How to do it?

**Comment by Res260** [comment]
Some clients will still send the credential for non-nla logons. This is the case for freerdp with the right arguments. The graphical login happens only if the credentials are not included in the RDP handshake.

**Comment by obilodeau** [comment]
I'm going to close this issue. @danielsantos1234 let us know if we haven't properly answered and we will re-open.
