### ISSUE TITLE
Question: NLA setup

### ISSUE THREAD

**Issue by danielsantos1234** [GoSecure/pyrdp#350]
How to setup a server for gathering credentials for targets where NLA is required?

**Comment by obilodeau** [comment]
Extract the RDP certificate from the target system and use it with pyrdp. How to do so is covered here: https://github.com/GoSecure/pyrdp/blob/master/docs/cert-extraction.md

**Comment by obilodeau** [comment]
I'm going to close this issue but if you feel some information is missing please reply to this issue and I will re-open it.

**Comment by danielsantos1234** [comment]
Is this possible to collect credentials without server's certificate and then terminate the connection with client?

**Comment by obilodeau** [comment]
No, we don't support that right now. [I've read](https://twitter.com/pythonresponder/status/1162814428850589697) that [Responder](https://github.com/lgandx/Responder) does. I'll open a new issue to track that feature request.

**Comment by obilodeau** [comment]
FYI: This was reported in #358 and implemented in #367
