### ISSUE TITLE
Broken player - qt.qpa.pluging: Could not load the QT platform plugin "xcb"

### ISSUE THREAD

**Issue by Norup123** [GoSecure/pyrdp#351]
On a fresh ubuntu 20.04.3 install i have tried installing the pyrdp. I followed the install guide with pip, and the mitm is working fine. When trying to run the player however i am presented with the following issue

```
~/pyrdp$ pyrdp-player.py -p 3000
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)

```

Any idea what could be the issue here? I assume something broke during the installation, but i tried running the command
`pip3 install -U -e '.[full]'` again, but get the same error

**Comment by Norup123** [comment]
Ran `sudo apt-get install '^libxcb.*-dev'` outside the venv and now it works

**Comment by obilodeau** [comment]
What is your desktop environment? I have an 20.04 LTS installed but w/o a GUI for now. I will try to add the correct dependency but I don't want to add `'^libxcb.*-dev'` as I think it will increase our docker image significantly and only a small part of it is required.

**Comment by Norup123** [comment]
![image](https://user-images.githubusercontent.com/54578187/131483266-0d211f56-a19e-4358-a09e-7079fc0d7eca.png)

**Comment by obilodeau** [comment]
I managed to reproduce the issue in a VM
![2021-08-31_10-22 issue 351](https://user-images.githubusercontent.com/546325/131510039-172aa3f6-8d36-4cdd-8024-9f5328ec36cd.png)

**Comment by obilodeau** [comment]
Running `export QT_DEBUG_PLUGINS=1` then running `pyrdp-player.py` again gave a good amount of helpful output including:
```
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/platforms" ...
Cannot load library /home/vagrant/pyrdp/venv/lib/python3.8/site-packages/PySide2/Qt/plugins/platforms/libqxcb.so: (libxcb-xinerama.so.0: cannot open shared object file: No such file or directory)
QLibraryPrivate::loadPlugin failed on "/home/vagrant/pyrdp/venv/lib/python3.8/site-packages/PySide2/Qt/plugins/platforms/libqxcb.so" : "Cannot load library /home/vagrant/pyrdp/venv/lib/python3.8/site-packages/PySide2/Qt/plugins/platforms/libqxcb.so: (libxcb-xinerama.so.0: cannot open shared object file: No such file or directory)"
```

If I install `libxcb-xinerama0` then the `pyrdp-player.py` starts working. This dependency is only a few kilobytes so I see no problem adding it.
