### ISSUE TITLE
account and password substitution problem

### ISSUE THREAD

**Issue by benny12312311** [GoSecure/pyrdp#393]
I use mitm to connect my windows server, but it needs to type correct user account and password to login.
Can I have any method that the person connecting to this server do not need to type correct user account and password or just press enter to login?

**Comment by Res260** [comment]
The argument to replace the username and the password is available when doing `pyrdp-mitm.py --help`

**Comment by obilodeau** [comment]
Note that this doesn't work if using `--auth ssp` for RDP connections that require Network Level Authentication (NLA) to work.
