### ISSUE TITLE
Landing Page rdp man in the middle

### ISSUE THREAD

**Issue by enimer85** [GoSecure/pyrdp#402]
I was testing out the various features of pyrdp-mitm and the one that I liked was the RDP Landing page discussed in the https://www.gosecure.net/blog/2018/12/19/rdp-man-in-the-middle-smile-youre-on-camera/. I was not able to get this working with the new releases of pyrdp and bettercap. for the landing page, i was using python's simple server and following the video process under the Chrismas prank landing page. This feature is really cool and it can really emphasize that RDP protection is also important to secure. I know how to configure step1 but in step2 setup landing page wasn't really clear. The only thing that i got from it is that we can create a simple http serve via python. 

Thanks for taking the time to review. just wanted to share my thoughts and if anyone and some insights. 

Thankss
enimer

**Comment by obilodeau** [comment]
Make PyRDP work without the bettercap integration first. It adds a lot of networking complexity. Make sure the basic works first.

The landing page is simply an HTTP page we made to display once the user connected to our RDP server. It has nothing to do with PyRDP itself. It was just a means to display our prank. We could have done an image and set it as the wallpaper of the Windows machine that we redirected users to.

What are you trying to do with PyRDP?

**Comment by enimer85** [comment]
The way I thought was happening was the minute that the victim signs in a web browser open up or even a dialog box pops up telling them what just happened. The way I saw it in the video made it look like something popped up when the victim logged in to the special box.

**Comment by enimer85** [comment]
gotchya. what if you don't have the means to have a destination? for example in a pentest what if all you have is your attack box? but don't have anything else and you want your attack box to be the rdp server there won't be a way to display the landing page. I am just thinking out loud and I appreciate your time Olivier.

**Comment by obilodeau** [comment]
You could run a Windows VM on your attack box and have PyRDP redirect to it. Right now, PyRDP cannot be its own RDP endpoint. I think some people tried to use it with an X11 RDP server implementation (so you could use a container instead of a full-size VM) but I didn't track their success there.

**Comment by enimer85** [comment]
thats an interesting thought. I will have to test that out and go from there. Thanks Olivier. I think we can close out this ticket. I appreciate the time.

**Comment by enimer85** [comment]
Hello Oliver,Has this been improved on?ThanksSent from my iPhoneOn Jun 20, 2022, at 9:57 AM, Olivier Bilodeau ***@***.***> wrote:﻿
You could run a Windows VM on your attack box and have PyRDP redirect to it. Right now, PyRDP cannot be its own RDP endpoint. I think some people tried to use it with an X11 RDP server implementation (so you could use a container instead of a full-size VM) but I didn't track their success there.
