### ISSUE TITLE
Can I return the information after the client connection is completed

### ISSUE THREAD

**Issue by rookie-z** [GoSecure/pyrdp#427]
Can I return information after the client connection is completed? Like xrdp, I do not see relevant information in the document or code

thank you!

![image](https://user-images.githubusercontent.com/47766331/207793439-1f0393d7-64f0-4012-a094-32cceb2d16ae.png)
![image](https://user-images.githubusercontent.com/47766331/207794615-938d8896-9c9e-4a7f-9778-e24dc5ece040.png)

**Comment by obilodeau** [comment]
What do you mean by _return information_? I don't understand. In the logs or inject something in the GUI that would be visible by the victim of the MITM?

**Comment by rookie-z** [comment]
Yes, return the graphic or qt interface to the MITM victim

**Comment by obilodeau** [comment]
Check what @spameier achieved in #426. It is similar to what you are trying to do I think.

**Comment by rookie-z** [comment]
Thank you. That's what I want. Thank you very much for your reply
