### ISSUE TITLE
replay file closing

### ISSUE THREAD

**Issue by gninjamaster** [GoSecure/pyrdp#431]
Trying to find out where the replay file is close when the client logout or disconnect from the RDP session.
[TCPMITM](https://github.com/GoSecure/pyrdp/blob/master/pyrdp/mitm/TCPMITM.py#L100) doesn't seem to call it during the disconnect event. When I check with the `lsof`, the file still open. Not sure if this intentional?

**Comment by obilodeau** [comment]
No, it could be a bug.

**Comment by obilodeau** [comment]
Please re-open when you are ready to investigate.
