### ISSUE TITLE
PySide2 incompatibility with Python 3.11

### ISSUE THREAD

**Issue by obilodeau** [GoSecure/pyrdp#436]
PySide2 is explicitly incompatible with Python 3.11. When doing a `pip install full` of PyRDP on a 3.11 install:

```
ERROR: Could not find a version that satisfies the requirement PySide2<6,>=5.12; extra == "full" (from pyrdp[full]) (from versions: none)
ERROR: No matching distribution found for PySide2<6,>=5.12; extra == "full"
```

From https://pypi.org/project/PySide2/:

![image](https://github.com/GoSecure/pyrdp/assets/546325/04926588-8711-4c73-b8d1-826196b252da)

QT (maintainers of PySide) are saying that 5.15.11 is now LTS which is no longer available in built form... See https://forum.qt.io/topic/144843/pyside2-shiboken2-support-for-python-3-11.

We will need to consider migrating to QT6 eventually...

As a workaround, make sure to install a 3.10.x Python.

**Comment by obilodeau** [comment]
Appears to only affect Windows since I installed PyRDP from source with python 3.11 today

**Comment by TiddlyWiddly** [comment]
Affects newest version of Kali on M1 too, unfortunately...

**Comment by obilodeau** [comment]
> Affects newest version of Kali on M1 too, unfortunately...

To be precise, it affects all versions of Kali M1 since PySide2 is not built for the M1 architecture: https://forum.qt.io/topic/124289/mac-m1-pyside-2-6-can-t-install-lib/12.

This would be a different issue but with the same fix.

**Comment by obilodeau** [comment]
> Affects newest version of Kali on M1 too, unfortunately...

@TiddlyWiddly you can try Kali on M1 again on master. It should work now.
