### ISSUE TITLE
AttributeError: module 'setuptools' has no attribute 'find_namespace_packages'

### ISSUE THREAD

**Issue by hackzaid** [GoSecure/pyrdp#65]
I get the following error when i try to install as per the instructions. Any work around to this?

`Traceback (most recent call last):
  File "setup.py", line 18, in <module>
    packages=setuptools.find_namespace_packages(include=["pyrdp", "pyrdp.*"]),
AttributeError: module 'setuptools' has no attribute 'find_namespace_packages'`

**Comment by Res260** [comment]
@xshill Can confirm, but I think it's because you have not upgraded setuptools:

`sudo pip3 install --upgrade setuptools` :)

**Comment by Res260** [comment]
Reference: https://github.com/GoSecure/pyrdp#installing

**Comment by hackzaid** [comment]
Was using the default pip which i can confirm its version 18.7 from python2.7. Let me get pip3 installed then will get back with my progress.

**Comment by Res260** [comment]
No problem, have a nice day!

**Comment by ehern96** [comment]
Hi @Res260,

I am running this code:

--------------------------------------------------------------------------------------------------
cd translation/tensorflow
IMAGE=`sudo docker build . | tail -n 1 | awk '{print $3}'`
SEED=1
NOW=`date "+%F-%T"`
sudo docker run \
    --runtime=nvidia \
    -v $(pwd)/translation/raw_data:/raw_data \
    -v $(pwd)/compliance:/mlperf/training/compliance \
    -e "MLPERF_COMPLIANCE_PKG=/mlperf/training/compliance" \
    -t -i $IMAGE "./run_and_time.sh" $SEED | tee benchmark-$NOW.log
--------------------------------------------------------------------------------------------------

and I get this error:

Processing /mlperf/training/compliance
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-9cjr0joi-build/setup.py", line 30, in <module>
        packages=setuptools.find_namespace_packages(include=['mllog*']),
    AttributeError: module 'setuptools' has no attribute 'find_namespace_packages'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-9cjr0joi-build/

I updated the setup tool just like you suggested above but it's not working. Any idea about this?

Thanks!

**Comment by obilodeau** [comment]
This has nothing to do with this project. Update `setuptools` to the latest version and **do not** tell us if it fixed it for you or not :wink:
