### ISSUE TITLE
Refactor logging

### ISSUE THREAD

**Issue by xshill** [GoSecure/pyrdp#72]
It seems very strange that we need 30-40 lines of code to set up loggers in both the player and MITM. There's probably a way to prepare loggers in the core pyrdp modules such that only minimal configuration has to be done at the start of the program.

Also, the ConnectionMetadataFilter cannot be used with the new way the MITM is structured.

**Comment by Res260** [comment]
IMO its not that big of a deal that the logger takes that many lines to setup, our logging architechture is kinda complex and works really well.

Still, there exist some alternatives, such as a logging configuration file which could reduce the number of code line (but probably increase the total lines)

And yeah the ConnectionMetadataFilter is quite important

**Comment by xshill** [comment]
I've begun making a couple small changes, mostly:

- Using formatters for injecting custom variables instead of filters (because filters are not inherited). Examples of variables are the sensor ID and the session ID. The formatters have default values for custom variables (e.g: if no session ID is provided, it says `GLOBAL`).
- Using LoggerAdapters to avoid passing repetitive arguments.

Basically, we initialize a logger with a custom formatter that has a `{sessionID}` argument. Depending on how it's called, `{sessionID}` will be replaced with:
- `GLOBAL`, if it's called without a `sessionID` argument, to indicate that it's a message related to the program in general, not a specific session
- A session ID if it's called within one of the MITM components. A logger adapter is used to make sure that the argument will always be there, so this is transparent to the components themselves.

I agree it's not necessarily a problem if it takes more than a few lines to set up logging, it's more that it seems ambiguous whether setting up the loggers is left to the library or the application:

- Method `prepare_pyrdp_logger` in `logging/log.py`
- Method `prepare_ssl_session_logger` in `logging/log.py`

I'd be fine with moving all logger preparation to the applications since all the config is really application-specific anyway.

The changes haven't been committed and pushed because I haven't updated the player and clonecert apps yet.

**Comment by Res260** [comment]
> Using formatters for injecting custom variables instead of filters
I didnt know it was possible :o 

Looks like good changes, looking forward to see them!

**Comment by xshill** [comment]
Just pushed the logging changes: 52379f53ebc82b1cc552c4b2aa791eee32fc094c
