### ISSUE TITLE
Exception launched when clipboard contents are huge

### ISSUE THREAD

**Issue by xshill** [GoSecure/pyrdp#86]
When trying to write back a clipboard PDU, an exception is launched because it's trying to write the entire contents of the clipboard in a single TPKT block. This happens with huge clipboard contents (bigger than 2**16 bytes).

**Comment by xshill** [comment]
This bug occurs because we have no way to fragment large messages that are sent to the player. With normal RDP traffic there is the virtual channel layer which fragments PDUs as necessary.

**Comment by Res260** [comment]
What do you mean by normal RDP traffic? This is not normal? 🤔

--Émilio

**Comment by xshill** [comment]
The RDP layer stack has the virtual channel layer to handle fragmentation, but the layer stack for recording does not.

**Comment by Res260** [comment]
So we should add the virtual channel layer to the recording?

**Comment by xshill** [comment]
Something like that. I'll look into it.

**Comment by xshill** [comment]
Fixed by adding a length field to the player message layer.
