### ISSUE TITLE
Can I play the replay files in the browser?

### ISSUE THREAD

**Issue by zhaozhiming** [GoSecure/pyrdp#90]
I have setup the `pyrdp` tools and generate the replay file with `pyrdp` suffix. But I found these files can only play in the replay client.

How can I play them in the browser? Or how can I convert them to video files?

Thanks.

**Comment by Res260** [comment]
For now, these replay file can only be replayed in the player. The fastest way to have a video copy of the replay file is by using a screen recorder while playing the replay.
