### ISSUE TITLE
Add info log when CredSSP is enforced

### ISSUE THREAD

**Issue by xshill** [GoSecure/pyrdp#95]
It looks like we don't even parse the negotiation response at all. We need to parse the response and check if CredSSP is enforced to provide more information to the user.

**Comment by Res260** [comment]
I think I was parsing the negotiation response in case of problem to print the error code? It was very basic though

**Comment by xshill** [comment]
We were parsing negotiation responses, but these are only for success responses. There's also a NegotiationFailure structure when connections fail, which we didn't parse.

**Comment by Res260** [comment]
Fixed in #102
